spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://localhost:3306/notification_service?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect:  org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group-v2
      client-id: notification-service-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.jsp.notification_service.kafka.OrderEvent"



server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
